server:
  port: 8989

spring:
  datasource:
      url: jdbc:mariadb://localhost:3306/react-spring
      username: root
      password: maria123
      driver-class-name: org.mariadb.jdbc.Driver

# JPA(Java Persistence API)
# # spring:
#   jpa:
#     database-platform: org.hibernate.dialect.MariaDBDialect
#     properties:
#       hibernate:
#         # "[format_sql]": true            #SQL 보기 좋게 출력
#         # "[user_sql_comments]": true     #SQL 생성시 주석 포함
#         # "[highlight_sql]": true         #SQL 색깔
#         # "[hbm2ddl.auto]": update
#         format_sql: true
#         use_sql_comments: true
#         highlight_sql: true
#         hbm2ddl.auto: update
#     open-in-view: true
#     show-sql: true                      # 콘솔 로그로 출력하려면

#Dialect 설정
# spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true          # 하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        format_sql: true        # 콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        use_sql_comments: true  # 디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.


  #default 1MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# logging level
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

# JWT ( JSON WEB TOKEN )
# spring:
    jwt:
      header: "Authorization"
      prefix: "Bearer "
      secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
      tokenExpirationTime: 18000

    project:
      folderPath: "files/"
